version: '3'

tasks:

  server:
    cmds:
      - poetry run python manage.py runserver

  createsuperuser:
    cmds:
      - poetry run python manage.py createsuperuser

  makemigrations:
    cmds:
      - poetry run python manage.py makemigrations

  requirements:
    cmds:
      - poetry export -f requirements.txt --output requirements.txt

  migrate:
    deps: [makemigrations]
    cmds:
      - poetry run python manage.py migrate